name: proje
description: Flutter ogrenme projesi


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.2
  path: ^1.8.0
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  editable: ^2.0.0

  flutter_slidable: ^0.6.0








  cupertino_icons: ^1.0.2
  turkish: ^0.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter_lints: ^1.0.0


flutter:


  uses-material-design: true


  assets:
         - assets/resimler/



